#ifndef __TCP_LOCK_REPORT__H_
#define __TCP_LOCK_REPORT__H_

enum LOCK_REPORT_ACTION {
	PROCESS_EVENT_LOCK_REPORT_RECV = 1,
};

enum LOCK_REASON {
	LOCK_REASON_CHARGE_FULL = 0,
	LOCK_REASON_PLUGOUT,
	LOCK_REASON_LOCKCMD,
	LOCK_REASON_TEMPERATURE_WARNING,
	LOCK_REASON_OVERLOAD,
	LOCK_REASON_LEAKAGE,
	LOCK_REASON_NOCHARGE
};

#endif

